# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Phrasebook-Loader-DBI
version:      0.04
version_from: lib/Data/Phrasebook/Loader/DBI.pm
installdirs:  site
requires:
    Data::Phrasebook:              0.18
    DBI:                           1.38
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
